# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := image_viewer tp1 tp2 tp3

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

image_viewer: 
	@echo "==== Building image_viewer ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f image_viewer.make

tp1: 
	@echo "==== Building tp1 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tp1.make

tp2: 
	@echo "==== Building tp2 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tp2.make

tp3: 
	@echo "==== Building tp3 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tp3.make

clean:
	@${MAKE} --no-print-directory -C . -f image_viewer.make clean
	@${MAKE} --no-print-directory -C . -f tp1.make clean
	@${MAKE} --no-print-directory -C . -f tp2.make clean
	@${MAKE} --no-print-directory -C . -f tp3.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   image_viewer"
	@echo "   tp1"
	@echo "   tp2"
	@echo "   tp3"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
